In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder 
import pandas as pd
import numpy as np

# 1. Load the mushroom dataset

In [2]:
data_file = "mushrooms_data.csv"
features_file = "mushroom_feature_names.csv"
data = pd.read_csv(data_file)
features = pd.read_csv(features_file, header=None)

features_list = features[0].tolist()

data.columns = features_list
data.replace("?", np.nan, inplace=True)

data

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        e         x           s         y       t    a               f   
1        e         b           s         w       t    l               f   
2        p         x           y         w       t    p               f   
3        e         x           s         g       f    n               f   
4        e         x           y         y       t    a               f   
...    ...       ...         ...       ...     ...  ...             ...   
8118     e         k           s         n       f    n               a   
8119     e         x           s         n       f    n               a   
8120     e         f           s         n       f    n               a   
8121     p         k           y         n       f    y               f   
8122     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         b          k  ...                        s   
1               c         b          n  ...                        s   
2               c         n          n  ...                        s   
3               w         b          k  ...                        s   
4               c         b          n  ...                        s   
...           ...       ...        ...  ...                      ...   
8118            c         b          y  ...                        s   
8119            c         b          y  ...                        s   
8120            c         b          n  ...                        s   
8121            c         n          b  ...                        k   
8122            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8118                      o                      o         p          o   
8119                      o                      o         p          n   
8120                      o                      o         p          o   
8121                      w                      w         p          w   
8122                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 n          n       g  
1              o         p                 n          n       m  
2              o         p                 k          s       u  
3              o         e                 n          a       g  
4              o         p                 k          n       g  
...          ...       ...               ...        ...     ...  
8118           o         p                 b          c       l  
8119           o         p                 b          v       l  
8120           o         p                 b          c       l  
8121           o         e                 w          v       l  
8122           o         p                 o          c       l  

[8123 rows x 23 columns]

# 2. Check the datatype of each featue in your dataset.

In [3]:
data.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

# 3. How many unique values does each feature have? What are the unique values for features: cap-color, class, and veil-type?

In [4]:
data.nunique()

class                        2
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   4
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

### What are the unique values for features: cap-color, class, and veil-type?

In [5]:
data["cap-color"].unique()

array(['y', 'w', 'g', 'n', 'e', 'p', 'b', 'u', 'c', 'r'], dtype=object)

In [6]:
data["class"].unique()

array(['e', 'p'], dtype=object)

In [7]:
data["veil-type"].unique()

array(['p'], dtype=object)

# 4. Later in this homework you will need to implement the Mahalanobis distance for your Bayesian classifier. Can you calculate any kind of distance between your samples now? why?
No , We need to encode features from categorcial to numerical then we can

# 5. Encode your features from chategorical to numerical using the labelEncoder API of the sklearn library. What are the values of cap-color now?

In [8]:
encoded_mushroom_data = data.copy()

label_encoder = LabelEncoder()

for column in encoded_mushroom_data.columns:
    if encoded_mushroom_data[column].dtype == "object":
        encoded_mushroom_data[column] = label_encoder.fit_transform(
            encoded_mushroom_data[column]
        )

print(encoded_mushroom_data)
unique_encoded_cap_color = encoded_mushroom_data["cap-color"].unique()
print("Encoded values of 'cap-color':", unique_encoded_cap_color)

      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         0          5            2          9        1     0   
1         0          0            2          8        1     3   
2         1          5            3          8        1     6   
3         0          5            2          3        0     5   
4         0          5            3          9        1     0   
...     ...        ...          ...        ...      ...   ...   
8118      0          3            2          4        0     5   
8119      0          5            2          4        0     5   
8120      0          2            2          4        0     5   
8121      1          3            3          4        0     8   
8122      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          0           4  ...   
1                   1             0          0           5  ...   
2                 

In [9]:
data.isnull().sum()

class                          0
cap-shape                      0
cap-surface                    0
cap-color                      0
bruises                        0
odor                           0
gill-attachment                0
gill-spacing                   0
gill-size                      0
gill-color                     0
stalk-shape                    0
stalk-root                  2480
stalk-surface-above-ring       0
stalk-surface-below-ring       0
stalk-color-above-ring         0
stalk-color-below-ring         0
veil-type                      0
veil-color                     0
ring-number                    0
ring-type                      0
spore-print-color              0
population                     0
habitat                        0
dtype: int64

# 1. Separate your dataset into feature (X) and labels(y). Here X will be your feature matrix.

In [10]:
X = encoded_mushroom_data.drop(columns="class")
y = encoded_mushroom_data["class"]

# 2. In order to evaluate you model, separate 20 percent as test set and the rest as training set.

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Now before implementing your model, what is the Bayes rule? How is it used in Bayesian classification? What is each term of this rule called?

P(Y∣X) = P(X∣Y)P(Y) / P(X)

Where:

- P(Y∣X) is the posterior probability of class given features.
- P(X∣Y) is the likelihood of features given class.
- P(Y) is the prior probability of class.
- P(X) is the evidence probability.


# 4. What are the model parameters of LDA and QDA classifiers? What is the role of each parameter?Between QDA and LDA, which one has potentially more parameters? why?

### Model Parameters:

#### LDA (Linear Discriminant Analysis):
1. **Mean Vectors (μ):** Represent the mean of each class in the feature space.
2. **Shared Covariance Matrix (Σ):** Assumes that all classes share the same covariance matrix, i.e., assumes equal covariance among classes.

#### QDA (Quadratic Discriminant Analysis):
1. **Mean Vectors (μ):** Same as LDA, representing the mean of each class in the feature space.
2. **Class-Specific Covariance Matrices (Σ):** Allows each class to have its own covariance matrix, making the decision boundary more flexible and potentially better fitting to the data.

### Role of Each Parameter:

- **Mean Vectors (μ):** Determine the central location of each class within the feature space.
- **Covariance Matrices (Σ):** Capture the spread and orientation of data within each class. LDA assumes a shared covariance matrix among classes, while QDA allows separate covariance matrices for each class.

### Comparison of Parameter Count:

- **LDA** has fewer parameters compared to **QDA** because it assumes a shared covariance matrix across all classes.
- **QDA** potentially has more parameters as it estimates a separate covariance matrix for each class, providing more flexibility in capturing distinct covariance structures.

### Potential Explanation:

QDA potentially has more parameters because it estimates a separate covariance matrix for each class. In scenarios with multiple classes or high-dimensional data, QDA's flexibility increases the parameter count compared to LDA, where the assumption of a shared covariance matrix reduces the overall parameter count.



# 5. Now that you are familiar with the parameters and differences of LDA and QDA, implement themfrom scratch.


## functions

In [12]:
def mahalanobis_distance(x, mean, covariance):
    diff = x - mean

    distance = np.sqrt(np.dot(np.dot(diff, np.linalg.inv(covariance)), diff.T))

    return distance

## LDA Implementation:

In [43]:
class LDA:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.class_means = []
        self.shared_covariance = np.zeros((X.shape[1], X.shape[1]))

        for c in self.classes:
            X_class = X[y == c]
            mean = np.mean(X_class, axis=0)
            self.class_means.append(mean)
            self.shared_covariance += np.cov(X_class, rowvar=False)

        self.shared_covariance /= len(self.classes)

    def predict(self, X):
        predictions = []
        for x in X:
            distances = []
            for _, mean in enumerate(self.class_means):
                distance = mahalanobis_distance(x, mean, self.shared_covariance)
                distances.append(distance)

            predictions.append(self.classes[np.argmin(distances)])

        return np.array(predictions)
    
    def get_parameters_count(self, X, y):
        n_features = X.shape[1]
        n_classes = len(np.unique(y))
        lda_params_count = n_features * n_classes + n_features**2
        return lda_params_count

## QDA Implementation:

In [44]:
class QDA:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.class_means = []
        self.class_covariances = []

        for c in self.classes:
            X_class = X[y == c]
            mean = np.mean(X_class, axis=0)
            self.class_means.append(mean)
            self.class_covariances.append(np.cov(X_class, rowvar=False))

    def predict(self, X):
        predictions = []
        for x in X:
            distances = []
            for idx, mean in enumerate(self.class_means):
                distance = mahalanobis_distance(x, mean, self.class_covariances[idx])
                distances.append(distance)

            predictions.append(self.classes[np.argmin(distances)])

        return np.array(predictions)
    
    def get_parameters_count(self, X, y):
        n_features = X.shape[1]
        n_classes = len(np.unique(y))
        qda_params_count = n_features * n_classes + n_classes * n_features**2
        return qda_params_count

# 6. Then classify the test and training sets using both LDA and QDA.

In [45]:
try:
    lda = LDA()
    lda.fit(X_train.to_numpy(), y_train.to_numpy())
    lda_predictions_train = lda.predict(X_train.to_numpy())
    lda_predictions_test = lda.predict(X_test.to_numpy())

    qda = QDA()
    qda.fit(X_train.to_numpy(), y_train.to_numpy())
    qda_predictions_train = qda.predict(X_train.to_numpy())
    qda_predictions_test = qda.predict(X_test.to_numpy())
except:
    print("Singular matrix problems detected")

# 7. Singular Covariance Matrix in Feature Matrices

A singular matrix is a square matrix that does not have an inverse. Put simply, for a matrix to be invertible, it must possess a unique inverse matrix that, when multiplied with the original matrix, results in an identity matrix.

### Causes of a Singular Covariance Matrix:

1. **Redundant or Linearly Dependent Features:**
   - Multicollinearity arises when one or more features are a linear combination of others.
   - Linear dependence causes the covariance matrix to lose rank.
   - Instances include identical or nearly identical features or one feature being a constant multiple of another, leading to singularity.

2. **High Dimensionality with Limited Samples:**
   - In high-dimensional spaces (more features) with few samples, the covariance matrix can become singular.
   - When the number of features approximates or exceeds the sample count, singularity may occur.

3. **Noise or Outliers:**
   - Outliers or noise in the dataset can impact covariance matrix calculation.
   - Presence of outliers, especially in small datasets, can significantly influence estimated covariance, potentially leading to singularity.


# 8. One reason for the covariance matrix to be singular is zero or very low variance over one featureamong the feature vectors (X). Meaning that this feature have the same value among all samples.This kind of features will give us no information to help classify our samples. So go back and and before splitting test and training sets, calculate the variance over each feature of your dataset and eliminate the ones with variance less than 0.01.


In [46]:
variances = X.var()

low_variance_features = variances[variances < 0.01].index

filtered_X = X.drop(columns=low_variance_features)

X_train, X_test, y_train, y_test = train_test_split(
    filtered_X, y, test_size=0.2, random_state=42
)

In [47]:
low_variance_features

Index(['veil-type'], dtype='object')

# 9. Now that you have fixed the singular matrix problem, repeat items 5 and 6.

In [48]:
lda = LDA()
lda.fit(X_train.to_numpy(), y_train.to_numpy())
lda_predictions_train = lda.predict(X_train.to_numpy())
lda_predictions_test = lda.predict(X_test.to_numpy())

qda = QDA()
qda.fit(X_train.to_numpy(), y_train.to_numpy())
qda_predictions_train = qda.predict(X_train.to_numpy())
qda_predictions_test = qda.predict(X_test.to_numpy())

# 10. Report accuracy, precision, recall, f1-score and the confusion matrix on both training and test sets for both LDA and QDA models. Which classifier performs better on mushroom dataset?


In [67]:
onfusion_matrix = np.zeros((2, 2), dtype=int)

In [58]:
def calculate_accuracy(y_true, y_pred):
    return sum(y_true == y_pred) / len(y_true)


def calculate_confusion_matrix(y_true, y_pred):
    unique_labels = np.unique(np.concatenate((y_true, y_pred)))
    num_labels = len(unique_labels)
    confusion_matrix = np.zeros((num_labels, num_labels), dtype=int)

    for i in range(len(y_true)):
        confusion_matrix[y_true[i], y_pred[i]] += 1

    return confusion_matrix


def calculate_precision_recall_f1(confusion_matrix):
    diagonal = confusion_matrix.diagonal()
    precision = diagonal / confusion_matrix.sum(axis=0)
    recall = diagonal / confusion_matrix.sum(axis=1)
    f1_score = 2 * (precision * recall) / (precision + recall)

    return precision, recall, f1_score

In [59]:

lda_predictions_train = lda.predict(X_train.to_numpy())
lda_predictions_test = lda.predict(X_test.to_numpy())

qda_predictions_train = qda.predict(X_train.to_numpy())
qda_predictions_test = qda.predict(X_test.to_numpy())


for model_name, y_true_train, y_pred_train, y_true_test, y_pred_test in [
    (
        "LDA - Training",
        y_train.to_numpy(),
        lda_predictions_train,
        y_test.to_numpy(),
        lda_predictions_test,
    ),
    (
        "LDA - Test",
        y_test.to_numpy(),
        lda_predictions_test,
        y_test.to_numpy(),
        lda_predictions_test,
    ),
    (
        "QDA - Training",
        y_train.to_numpy(),
        qda_predictions_train,
        y_test.to_numpy(),
        qda_predictions_test,
    ),
    (
        "QDA - Test",
        y_test.to_numpy(),
        qda_predictions_test,
        y_test.to_numpy(),
        qda_predictions_test,
    ),
]:
    print(f"Evaluation metrics for {model_name}:")
    if "Training" in model_name:
        y_true, y_pred = y_true_train, y_pred_train
    else:
        y_true, y_pred = y_true_test, y_pred_test

    accuracy = calculate_accuracy(y_true, y_pred)
    print(f"Accuracy: {accuracy:.4f}")

    confusion_mat = calculate_confusion_matrix(y_true, y_pred)
    print("Confusion Matrix:")
    print(confusion_mat)
    precision, recall, f1_score = calculate_precision_recall_f1(confusion_mat)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-score:", f1_score)
    print("\n")

Evaluation metrics for LDA - Training:
Accuracy: 0.9460
Confusion Matrix:
[[3197  158]
 [ 193 2950]]
Precision: [0.94306785 0.94916345]
Recall: [0.95290611 0.9385937 ]
F1-score: [0.94796145 0.94384898]


Evaluation metrics for LDA - Test:
Accuracy: 0.9471
Confusion Matrix:
[[810  43]
 [ 43 729]]
Precision: [0.94958968 0.94430052]
Recall: [0.94958968 0.94430052]
F1-score: [0.94958968 0.94430052]


Evaluation metrics for QDA - Training:
Accuracy: 0.9889
Confusion Matrix:
[[3355    0]
 [  72 3071]]
Precision: [0.97899037 1.        ]
Recall: [1.         0.97709195]
F1-score: [0.98938366 0.98841326]


Evaluation metrics for QDA - Test:
Accuracy: 0.9883
Confusion Matrix:
[[853   0]
 [ 19 753]]
Precision: [0.97821101 1.        ]
Recall: [1.        0.9753886]
F1-score: [0.98898551 0.98754098]




QDA outperforms LDA on the mushroom dataset, displaying superior accuracy and precision-recall metrics, making it the preferred classifier for this specific classification task.

# 11. According to your confusion matrices, how many samples are misclassified in each classifier? Are these misclassified samples as FP (False Positive) or FN (False Negative)? Which one is more important in the task of classifying poisonous mushrooms?


In [60]:
def calculate_misclassified_samples(confusion_matrix):
    return np.sum(confusion_matrix) - np.trace(confusion_matrix)


def calculate_false_positives(confusion_matrix, label_index):
    false_positives = (
        np.sum(confusion_matrix[:, label_index])
        - confusion_matrix[label_index, label_index]
    )
    return false_positives


def calculate_false_negatives(confusion_matrix, label_index):
    false_negatives = (
        np.sum(confusion_matrix[label_index, :])
        - confusion_matrix[label_index, label_index]
    )
    return false_negatives

In [61]:
for model_name, y_true_train, y_pred_train, y_true_test, y_pred_test in [
    (
        "LDA - Training",
        y_train.to_numpy(),
        lda_predictions_train,
        y_test.to_numpy(),
        lda_predictions_test,
    ),
    (
        "LDA - Test",
        y_test.to_numpy(),
        lda_predictions_test,
        y_test.to_numpy(),
        lda_predictions_test,
    ),
    (
        "QDA - Training",
        y_train.to_numpy(),
        qda_predictions_train,
        y_test.to_numpy(),
        qda_predictions_test,
    ),
    (
        "QDA - Test",
        y_test.to_numpy(),
        qda_predictions_test,
        y_test.to_numpy(),
        qda_predictions_test,
    ),
]:
    if "Training" in model_name:
        y_true, y_pred = y_true_train, y_pred_train
    else:
        y_true, y_pred = y_true_test, y_pred_test

    confusion_mat = calculate_confusion_matrix(y_true, y_pred)
    misclassified = calculate_misclassified_samples(confusion_mat)

    print(f"Evaluation metrics for {model_name}:")
    print("Confusion Matrix:")
    print(confusion_mat)

    label_index = 1  # Assuming 'poisonous' is the second class (index 1)
    false_positives = calculate_false_positives(confusion_mat, label_index)
    false_negatives = calculate_false_negatives(confusion_mat, label_index)

    print(f"False Positives: {false_positives}")
    print(f"False Negatives: {false_negatives}")

    if false_negatives > false_positives:
        print("False Negatives are more critical in classifying poisonous mushrooms.")
    elif false_positives > false_negatives:
        print("False Positives are more critical in classifying poisonous mushrooms.")
    else:
        print("False Positives and False Negatives have equal importance.")

    print(f"Misclassified samples: {misclassified}")
    print("\n")

Evaluation metrics for LDA - Training:
Confusion Matrix:
[[3197  158]
 [ 193 2950]]
False Positives: 158
False Negatives: 193
False Negatives are more critical in classifying poisonous mushrooms.
Misclassified samples: 351


Evaluation metrics for LDA - Test:
Confusion Matrix:
[[810  43]
 [ 43 729]]
False Positives: 43
False Negatives: 43
False Positives and False Negatives have equal importance.
Misclassified samples: 86


Evaluation metrics for QDA - Training:
Confusion Matrix:
[[3355    0]
 [  72 3071]]
False Positives: 0
False Negatives: 72
False Negatives are more critical in classifying poisonous mushrooms.
Misclassified samples: 72


Evaluation metrics for QDA - Test:
Confusion Matrix:
[[853   0]
 [ 19 753]]
False Positives: 0
False Negatives: 19
False Negatives are more critical in classifying poisonous mushrooms.
Misclassified samples: 19




In [62]:
def calculate_class_priors(y):
    _, counts = np.unique(y, return_counts=True)
    return counts / len(y)


def calculate_class_means(X, y):
    class_means = []
    for c in np.unique(y):
        X_class = X[y == c]
        mean = np.mean(X_class, axis=0)
        class_means.append(mean)
    return np.array(class_means)


def calculate_shared_covariance(X, y):
    class_means = calculate_class_means(X, y)
    S_W = np.zeros((X.shape[1], X.shape[1]))
    for c, mean in zip(np.unique(y), class_means):
        X_class = X[y == c]
        S_W += np.cov(X_class, rowvar=False) * len(X_class)
    return S_W / len(y)

## Linear Discriminant Analysis (LDA) Model Parameters

In [63]:
print("Linear Discriminant Analysis (LDA) Model Parameters:")
print("Class Priors (π_k):", calculate_class_priors(y_train))
print("Class Means (μ_k):", lda.class_means)
print("Shared Covariance Matrix (Σ):", calculate_shared_covariance(X_train, y_train))

Linear Discriminant Analysis (LDA) Model Parameters:
Class Priors (π_k): [0.51631271 0.48368729]
Class Means (μ_k): [array([3.2509687 , 1.60983607, 4.56125186, 0.65692996, 4.33681073,
       0.9538003 , 0.28166915, 0.06467958, 6.61311475, 0.61728763,
       1.34783905, 1.77764531, 1.79880775, 6.09180328, 6.04560358,
       1.93025335, 1.12459016, 3.01102832, 3.19225037, 3.28643815,
       1.14307004]), array([3.43779828, 2.05345212, 4.43970729, 0.15972001, 3.93445752,
       0.99427299, 0.03054407, 0.57270124, 2.90136812, 0.51606745,
       1.94654788, 1.36302895, 1.39548202, 5.51956729, 5.51034044,
       2.00254534, 1.00668151, 1.52656697, 4.03627108, 4.01877187,
       1.89436844])]
Shared Covariance Matrix (Σ): [[ 2.55176144e+00 -1.19925111e-01 -2.09604908e-01 -4.14284591e-03
  -8.44254879e-02  2.07480365e-02  2.22916413e-02  1.73187614e-02
   1.31230549e-01  4.69718342e-02 -2.29884697e-01 -1.40554509e-02
  -1.82849449e-02 -7.79284108e-02 -7.19868003e-02  2.85132661e-02
  -3.557556

## Quadratic Discriminant Analysis (QDA) Model Parameters

In [64]:
print("Quadratic Discriminant Analysis (QDA) Model Parameters:")
print("Class Priors (π_k):", calculate_class_priors(y_train))
print("Class Means (μ_k):", qda.class_means)
print("Class-Specific Covariance Matrices (Σ_k):", qda.class_covariances)
print("\n")

Quadratic Discriminant Analysis (QDA) Model Parameters:
Class Priors (π_k): [0.51631271 0.48368729]
Class Means (μ_k): [array([3.2509687 , 1.60983607, 4.56125186, 0.65692996, 4.33681073,
       0.9538003 , 0.28166915, 0.06467958, 6.61311475, 0.61728763,
       1.34783905, 1.77764531, 1.79880775, 6.09180328, 6.04560358,
       1.93025335, 1.12459016, 3.01102832, 3.19225037, 3.28643815,
       1.14307004]), array([3.43779828, 2.05345212, 4.43970729, 0.15972001, 3.93445752,
       0.99427299, 0.03054407, 0.57270124, 2.90136812, 0.51606745,
       1.94654788, 1.36302895, 1.39548202, 5.51956729, 5.51034044,
       2.00254534, 1.00668151, 1.52656697, 4.03627108, 4.01877187,
       1.89436844])]
Class-Specific Covariance Matrices (Σ_k): [array([[ 3.02047834e+00, -9.85336813e-02, -4.73635679e-01,
         2.79859802e-02,  2.08826883e-01,  3.96243736e-02,
         1.39637970e-02,  2.04352389e-02,  1.49003392e-01,
         1.35433457e-01, -2.20596445e-01, -2.85561560e-02,
        -2.40298525e-02

How many parameters are there?

In [65]:
lda_params_count = lda.get_parameters_count(X_train, y_train)
qda_params_count = qda.get_parameters_count(X_train, y_train)

print("Number of parameters in LDA:", lda_params_count)
print("Number of parameters in QDA:", qda_params_count)

Number of parameters in LDA: 483
Number of parameters in QDA: 924


How many parameters would you have if you used logistic regression?


numbers of features + 1

In [66]:
X.shape[1] + 1

23